### ISSUE TITLE
Use SAM abbreviation mark

### ISSUE THREAD

**Issue by esoleyman** [esoleyman/cldr-syriac#2]
Investigate using SAM abbreviation mark (070F ![070F](https://user-images.githubusercontent.com/6634387/126488022-5e60c3f6-61f1-4f3f-9cac-aedcce7280d5.png)) for numbers, dates and times

![sam_numeric](https://user-images.githubusercontent.com/6634387/126487995-a1446321-cf54-4786-99b0-1415a7bf2ef2.png)

**Comment by SargisYonan** [comment]
Relating: https://github.com/esoleyman/cldr-syriac/issues/3

**Comment by esoleyman** [comment]
Close in favor of #3
